# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5e1c9943df1645510512aac57c1e4c6df244a76291360d4bbfc16da613575fbf7a9cba3d6f3115f03df0c6e267bcc4656552b4c2417d22a6f42e41dbba211ca

test:
  secret_key_base: 541ef349ec1ac08367196731a1b6c74dbbd3069971df19577e1f538fe91b5bd793dd34280a971b1d07256f2cc13c8a2dec3ef39923b130b8b923a883a0a6ff03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
